"""Simplified one-shot pipeline.

The entire static is generated by a single Nano Banana Pro call. The reasoning
layer (Claude) is used only to craft the best possible prompt — analyzing the
brief, reference image, and brand guide to write a detailed creative direction.

Architecture:
  1. (Optional) Reference Parser — Claude vision extracts layout from reference
  2. Prompt assembly — code templates the NBP prompt from brief + reference + brand
  3. ONE Nano Banana Pro call — product reference + prompt → finished static

Total: 1–2 API calls. That's it.
"""
from __future__ import annotations

import uuid
from pathlib import Path

from rich.console import Console
from rich.panel import Panel

from .brand.pack import list_exemplar_statics, load_design_guide
from .brand.tokens import BACKGROUND_MOODS, COLORS
from .clients.nano_banana import edit_image
from .models import BuildInput, CopyDeck, ReferenceLayout
from .product.props import get_prop
from .product.registry import hero_silhouette, label_references

console = Console()
OUTPUTS_DIR = Path(__file__).resolve().parents[1] / "outputs"

VARIATION_HINTS = [
    "",
    "STYLE VARIATION: Emphasize raw ingredient textures — show ingredients prominently near the jar.",
    "STYLE VARIATION: Dramatic lighting with deeper shadows, premium editorial feel.",
    "STYLE VARIATION: Airy, minimal composition with generous whitespace and softer tones.",
]

# Per-variant background palettes — stays within the beige → white range the brand owns.
# Indexed by variant_index % len. Each entry is (human-readable name, light hex, dark hex).
BACKGROUND_PALETTES = [
    ("warm cream",       "#F5F0E8", "#EDE8DC"),
    ("pure studio white", "#FFFFFF", "#F7F5F1"),
    ("cool ivory",       "#F8F6F2", "#EFEEE9"),
    ("warm taupe beige", "#E8DFCF", "#D9CEB9"),
]


def run(inp: BuildInput) -> str:
    """Run the one-shot pipeline. Returns the path to the final static."""
    run_id = uuid.uuid4().hex[:10]
    console.print(Panel.fit(f"[bold cyan]MM Statics Builder (one-shot)[/] — run [yellow]{run_id}[/]"))

    # 1. Parse reference layout (optional)
    ref_layout: ReferenceLayout | None = None
    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        console.print("[1] Parsing reference layout…")
        try:
            from .agents.reference_parser import run as parse_ref
            ref_layout = parse_ref(Path(inp.reference_static_path))
            console.print(f"    mood: {ref_layout.mood}")
        except Exception as e:
            console.print(f"    ⚠ skipped: {e}")

    # 2. Assemble the prompt
    console.print("[2] Building prompt…")
    prompt = _build_prompt(inp, ref_layout)

    # 3. Gather reference images
    product_path = hero_silhouette()
    label_refs = label_references(max_count=5)
    images: list[Path] = [product_path] + label_refs
    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        images.append(Path(inp.reference_static_path))
    images += list_exemplar_statics(max_count=2)
    console.print(
        f"    {len(images)} reference images "
        f"(product + {len(label_refs)} label close-ups + style refs)"
    )

    # 4. One NBP call
    out_path = OUTPUTS_DIR / "statics" / f"static_{run_id}.png"
    console.print("[3] Generating static (Nano Banana Pro)…")
    edit_image(
        prompt=prompt,
        input_images=images,
        out_path=out_path,
        aspect_ratio=inp.format,
    )

    console.print(Panel.fit(f"[bold green]✓ Done[/]\n{out_path}"))
    return str(out_path)


def run_variant(
    inp: BuildInput,
    variant_index: int = 0,
    run_id: str | None = None,
    extra_style_refs: list[Path] | None = None,
    force_human: bool | None = None,
    parsed_reference: ReferenceLayout | None = None,
) -> str:
    """Generate a single variant. Called by the web app for multi-variant runs.

    Silent (no Rich output) — designed to run in a background thread.

    If a reference image is attached and `match_mode == "closely_match"`, the
    reference is parsed once (by the caller, ideally) and its bboxes are
    injected into the prompt as strict coordinates. In `inspired` mode, only
    palette + mood are forwarded.
    """
    rid = run_id or uuid.uuid4().hex[:10]

    # Closely-match mode should converge across variants, so skip the style
    # variation hints. Inspired mode uses them to diverge.
    if inp.match_mode == "closely_match" and inp.reference_static_path:
        hint = ""
    else:
        hint = VARIATION_HINTS[variant_index % len(VARIATION_HINTS)]

    # Parse reference on first variant if caller didn't pre-parse.
    ref = parsed_reference
    if (
        ref is None
        and inp.reference_static_path
        and Path(inp.reference_static_path).exists()
    ):
        try:
            from .agents.reference_parser import run as parse_ref
            ref = parse_ref(Path(inp.reference_static_path))
        except Exception:
            ref = None

    # Pick a background palette for this variant. Closely-match locks onto
    # the reference's own palette (first hex) if parsed.
    if inp.match_mode == "closely_match" and ref and ref.palette_hex:
        bg_palette = ("reference-matched", ref.palette_hex[0], ref.palette_hex[-1])
    else:
        bg_palette = BACKGROUND_PALETTES[variant_index % len(BACKGROUND_PALETTES)]

    prompt = _build_prompt(
        inp,
        ref=ref,
        variation_hint=hint,
        force_human=force_human,
        bg_palette=bg_palette,
    )

    product_path = hero_silhouette()
    label_refs = label_references(max_count=5)
    images: list[Path] = [product_path] + label_refs

    # Ingredient photos
    for kw in inp.ingredients:
        prop = get_prop(kw)
        if prop and prop.image_path.exists():
            images.append(prop.image_path)

    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        images.append(Path(inp.reference_static_path))

    images += list_exemplar_statics(max_count=2)

    # Approved outputs as extra style references
    for ref_path in extra_style_refs or []:
        if ref_path.exists():
            images.append(ref_path)

    out_path = OUTPUTS_DIR / "statics" / f"app_{rid}_v{variant_index}.png"
    edit_image(prompt=prompt, input_images=images, out_path=out_path, aspect_ratio=inp.format)
    return str(out_path)


def _build_prompt(
    inp: BuildInput,
    ref: ReferenceLayout | None,
    variation_hint: str = "",
    force_human: bool | None = None,
    bg_palette: tuple[str, str, str] | None = None,
) -> str:
    copy = inp.copy_deck
    # Reference is active if we have a parsed layout OR if a reference image path exists
    has_reference = (ref is not None) or bool(
        inp.reference_static_path and Path(inp.reference_static_path).exists()
    )
    # "closely_match" only kicks in when a reference exists
    close_match = (inp.match_mode == "closely_match") and has_reference

    # Copy block
    copy_lines = [f'- Headline: "{copy.headline}" — upper area, very bold, 2 lines, large']
    if copy.subhead:
        copy_lines.append(f'- Subhead: "{copy.subhead}" — below headline, regular weight, smaller')
    if copy.bottom_strip:
        strip_text = "  |  ".join(copy.bottom_strip[:3])
        copy_lines.append(f'- Bottom strip: "{strip_text}" — centered at very bottom, small, semi-bold')
    if copy.cta:
        copy_lines.append(f'- CTA: "{copy.cta}" — small black pill button below subhead')
    copy_lines.append('- Logo: "man matters®" — top-left, small, lowercase bold sans-serif')
    copy_lines.append('- Thin horizontal rule line above the bottom strip')
    copy_block = "\n".join(copy_lines)

    # Reference-informed composition
    if close_match:
        comp_block = _close_match_block(ref, inp.reference_static_path)
    elif has_reference:
        ref_detail = ""
        if ref:
            palette_line = (
                f"\n- Reference palette (use these tones): {', '.join(ref.palette_hex)}"
                if ref.palette_hex else ""
            )
            ref_detail = (
                f"\n- Reference mood: {ref.mood}"
                f"\n- Reference notes: {ref.notes}"
                f"{palette_line}"
            )
        comp_block = f"""COMPOSITION (inspired by reference — take the vibe, not the exact layout):
- One of the attached images is a REFERENCE STATIC. Use it as loose inspiration for mood, tonality, and overall feel — NOT as a strict layout blueprint.
- You are free to improvise the composition. Keep the brand's clean editorial style.
- Do NOT copy the reference's text, branding, product, or exact element positions.{ref_detail}"""
    else:
        comp_block = """COMPOSITION:
- Jar: center-right, upright, hero, facing camera. Takes up ~40-50% of canvas height.
- Headline: upper-left third, bold, 2 lines
- Subhead: directly below headline, ~55% of headline size
- Clear breathing room between text and product
- No text overlapping the jar"""

    # Ingredient block
    ingredient_block = ""
    if inp.ingredients:
        ing_lines = []
        for kw in inp.ingredients:
            prop = get_prop(kw)
            if prop:
                ing_lines.append(f"- {prop.display_name}: {prop.description}")
        if ing_lines:
            ingredient_block = (
                "\nFEATURED INGREDIENTS (arrange these as real, physical elements near the jar):\n"
                + "\n".join(ing_lines)
                + "\nUse the attached ingredient reference photos for accurate rendering. "
                "Present them in small glass or ceramic dishes, or scattered directly on the surface.\n"
            )

    # Human figure
    include_human = force_human if force_human is not None else (inp.template_hint in ("D", "J", "F"))
    human_block = ""
    if include_human:
        human_block = """
HUMAN FIGURE:
- Include an Indian man, age 25-35, in the composition
- Natural, authentic look — not stock-photo or AI-plastic
- Natural skin texture with pores, realistic hair, slight asymmetry
- Expression and pose should match the emotional tone of the headline
- The human should feel integrated into the scene, not pasted
- Crop strategy: upper body or half body; avoid showing hands holding the product to prevent finger artifacts
- AVOID: plastic/waxy skin, extra fingers, perfect symmetry, uncanny expressions"""
    elif not include_human:
        human_block = "\nHUMAN FIGURE: none. Do NOT include any human, hand, or figure."

    # Background mood
    if inp.template_hint in ("C", "D"):
        bg = "dark charcoal/moody (#2D2825), dramatic lighting"
    elif inp.template_hint in ("E",):
        bg = "mountain/sky outdoor photography, aspirational"
    elif bg_palette is not None:
        name, light_hex, dark_hex = bg_palette
        bg = (
            f"{name} — a soft gradient between {light_hex} and {dark_hex}, "
            "soft studio lighting from upper-right. Stay within this beige → white range; "
            "no grey, no green, no blue tint."
        )
    else:
        bg = "warm beige/cream (#F5F0E8 to #EDE8DC), soft studio lighting from upper-right"

    return f"""You are creating a premium advertising static for Man Matters Shilajit Gummies.

PRODUCT: Image 1 is the main product jar. The next images are close-up photos of the SAME jar from different angles showing label details. Study ALL of these carefully — every word, icon, and detail on the label must be reproduced accurately in your output. The jar has a matte black body and white cap. Render EXACTLY ONE jar — never duplicate it.

EXACT TEXT ON THE JAR LABEL (reproduce these words precisely on the jar):
Front panel (top to bottom):
- [Gluten Free icon] top-left
- "man matters®" — brand logo, large, lowercase, bold, white on black
- "active nutrition" — sub-brand, small, white, centered
- "SHILAJIT GUMMIES" — product name, large bold white text, centered
- "— ShilAbsorb™ Shilajit" — ingredient line with em-dash
- "— KSM-66® Ashwagandha" — ingredient line with em-dash
- [NO ADDED SUGAR badge] — small green/white badge, right side
- Three icons in a row: "Potent Fulvic Acid" | "100% Natural" | "Superior Absorption"
- "NUTRACEUTICAL" — small caps
- "Tamarind Flavour | ADULT" — small text
- "60 N Gummies | 1 month supply" — small text
- "MADE IN INDIA" — very small, bottom-right

{_reference_header(close_match, has_reference)}

COPY TO RENDER (render every word exactly as written — no paraphrasing, no omitting, no extra words):
{copy_block}

BRAND GUIDELINES:
- Background: {bg}
- Text: near-black (#1C1C1C) for headlines, medium grey (#5A5A5A) for subhead
- Typography: clean geometric sans-serif like Inter or GT America. NO serif fonts ever.
- Aesthetic: premium, minimal, editorial product photography. Indian D2C wellness brand. Clean, confident, modern-masculine.

{comp_block}
{ingredient_block}
{human_block}
{variation_hint}

HARD RULES — violation is disqualifying:
- Exactly ONE jar. Not two. Not a pair.
- Every word of copy rendered exactly as written above — no synonyms, no missing words
- Sans-serif only throughout
- No extra text, claims, taglines, icons, or decorative elements beyond what is listed
- All text must be crisp, readable, correctly formed
- Product label on the jar must be as close to image 1 as possible

FORMAT: {inp.format} aspect ratio. High resolution, sharp, no grain.
OUTPUT: a single complete advertising static ready to ship."""


def _reference_header(close_match: bool, has_reference: bool) -> str:
    if close_match:
        return (
            "CRITICAL — REFERENCE STATIC: One of the images after the label close-ups is a "
            "REFERENCE STATIC. This is your STRICT LAYOUT BLUEPRINT. Replicate its compositional "
            "structure EXACTLY — product position, headline position, subhead position, bottom "
            "strip position, visual hierarchy, whitespace balance, element proportions. "
            "Match the reference's palette. Do NOT copy its text, branding, or product — only "
            "spatial layout and tonality. The remaining images are Man Matters brand exemplars."
        )
    if has_reference:
        return (
            "INSPIRATION REFERENCE: One of the images after the label close-ups is an "
            "INSPIRATION STATIC. Take loose mood and tonality cues from it — DO NOT copy its "
            "layout, text, branding, or product. Feel free to improvise composition. "
            "Remaining images are Man Matters brand exemplars for visual tone."
        )
    return (
        "STYLE REFERENCES: Remaining images are Man Matters brand exemplars — match their "
        "visual tone, palette, and editorial aesthetic."
    )


def _close_match_block(ref: ReferenceLayout | None, ref_path: str | None) -> str:
    """Build the strict compositional block for closely_match mode.

    When `ref` is a parsed ReferenceLayout, we inject normalized bbox coordinates
    so NBP has numeric placement targets. When parsing failed but a reference
    image is still attached, we fall back to prose-strict language.
    """
    lines = ["COMPOSITION (STRICT — you MUST replicate the reference's structure):"]
    lines.append(
        "- The REFERENCE STATIC attached is your LAYOUT BLUEPRINT. "
        "Match its element positions, proportions, and spatial hierarchy."
    )

    if ref is not None:
        def _fmt(box):
            if box is None:
                return None
            return (
                f"x={box.x:.2f}, y={box.y:.2f}, "
                f"w={box.w:.2f}, h={box.h:.2f} (fractions of canvas)"
            )

        coord_lines: list[str] = []
        if ref.product:
            coord_lines.append(f"- Product jar position: {_fmt(ref.product)}")
        if ref.headline:
            coord_lines.append(f"- Headline block position: {_fmt(ref.headline)}")
        if ref.subhead:
            coord_lines.append(f"- Subhead block position: {_fmt(ref.subhead)}")
        if ref.bottom_strip:
            coord_lines.append(f"- Bottom strip position: {_fmt(ref.bottom_strip)}")
        if coord_lines:
            lines.append("")
            lines.append("EXACT NORMALIZED COORDINATES FROM THE REFERENCE:")
            lines.extend(coord_lines)
            lines.append(
                "- Each coordinate is a fraction of canvas width/height. "
                "Place each element so its top-left corner lands at (x, y) and its "
                "dimensions are (w, h). Stay within ±3% of these targets."
            )

        if ref.logo_position:
            lines.append(f"- Logo corner (from reference): {ref.logo_position}")
        if ref.mood:
            lines.append(f"- Reference mood: {ref.mood}")
        if ref.notes:
            lines.append(f"- Reference notes: {ref.notes}")
        if ref.palette_hex:
            lines.append(
                f"- Reference palette (use these tones): {', '.join(ref.palette_hex)}"
            )
    else:
        lines.append(
            "- Study the reference image carefully. Replicate its product placement, "
            "headline placement, subhead placement, and bottom-strip placement "
            "within ±3% of the original positions."
        )

    lines.append(
        "- Do NOT copy the reference's text, branding, product, or logo. "
        "Copy only its spatial layout and tonality."
    )
    return "\n".join(lines)
