"""Simplified one-shot pipeline.

The entire static is generated by a single Nano Banana Pro call. The reasoning
layer (Claude) is used only to craft the best possible prompt — analyzing the
brief, reference image, and brand guide to write a detailed creative direction.

Architecture:
  1. (Optional) Reference Parser — Claude vision extracts layout from reference
  2. Prompt assembly — code templates the NBP prompt from brief + reference + brand
  3. ONE Nano Banana Pro call — product reference + prompt → finished static

Total: 1–2 API calls. That's it.
"""
from __future__ import annotations

import uuid
from pathlib import Path

from rich.console import Console
from rich.panel import Panel

from .brand.pack import list_exemplar_statics, load_design_guide
from .brand.tokens import BACKGROUND_MOODS, COLORS
from .clients.nano_banana import edit_image
from .models import BuildInput, CopyDeck, ReferenceLayout
from .product.props import get_prop
from .product.registry import hero_silhouette, label_references

console = Console()
OUTPUTS_DIR = Path(__file__).resolve().parents[1] / "outputs"

VARIATION_HINTS = [
    "",
    "STYLE VARIATION: Emphasize raw ingredient textures — show ingredients prominently near the jar.",
    "STYLE VARIATION: Dramatic lighting with deeper shadows, premium editorial feel.",
    "STYLE VARIATION: Airy, minimal composition with generous whitespace and softer tones.",
]


def run(inp: BuildInput) -> str:
    """Run the one-shot pipeline. Returns the path to the final static."""
    run_id = uuid.uuid4().hex[:10]
    console.print(Panel.fit(f"[bold cyan]MM Statics Builder (one-shot)[/] — run [yellow]{run_id}[/]"))

    # 1. Parse reference layout (optional)
    ref_layout: ReferenceLayout | None = None
    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        console.print("[1] Parsing reference layout…")
        try:
            from .agents.reference_parser import run as parse_ref
            ref_layout = parse_ref(Path(inp.reference_static_path))
            console.print(f"    mood: {ref_layout.mood}")
        except Exception as e:
            console.print(f"    ⚠ skipped: {e}")

    # 2. Assemble the prompt
    console.print("[2] Building prompt…")
    prompt = _build_prompt(inp, ref_layout)

    # 3. Gather reference images
    product_path = hero_silhouette()
    label_refs = label_references(max_count=5)
    images: list[Path] = [product_path] + label_refs
    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        images.append(Path(inp.reference_static_path))
    images += list_exemplar_statics(max_count=2)
    console.print(
        f"    {len(images)} reference images "
        f"(product + {len(label_refs)} label close-ups + style refs)"
    )

    # 4. One NBP call
    out_path = OUTPUTS_DIR / "statics" / f"static_{run_id}.png"
    console.print("[3] Generating static (Nano Banana Pro)…")
    edit_image(
        prompt=prompt,
        input_images=images,
        out_path=out_path,
        aspect_ratio=inp.format,
    )

    console.print(Panel.fit(f"[bold green]✓ Done[/]\n{out_path}"))
    return str(out_path)


def run_variant(
    inp: BuildInput,
    variant_index: int = 0,
    run_id: str | None = None,
    extra_style_refs: list[Path] | None = None,
    force_human: bool | None = None,
) -> str:
    """Generate a single variant. Called by the web app for multi-variant runs.

    Silent (no Rich output) — designed to run in a background thread.
    """
    rid = run_id or uuid.uuid4().hex[:10]
    hint = VARIATION_HINTS[variant_index % len(VARIATION_HINTS)]

    prompt = _build_prompt(inp, ref=None, variation_hint=hint, force_human=force_human)

    product_path = hero_silhouette()
    label_refs = label_references(max_count=5)
    images: list[Path] = [product_path] + label_refs

    # Ingredient photos
    for kw in inp.ingredients:
        prop = get_prop(kw)
        if prop and prop.image_path.exists():
            images.append(prop.image_path)

    if inp.reference_static_path and Path(inp.reference_static_path).exists():
        images.append(Path(inp.reference_static_path))

    images += list_exemplar_statics(max_count=2)

    # Approved outputs as extra style references
    for ref_path in extra_style_refs or []:
        if ref_path.exists():
            images.append(ref_path)

    out_path = OUTPUTS_DIR / "statics" / f"app_{rid}_v{variant_index}.png"
    edit_image(prompt=prompt, input_images=images, out_path=out_path, aspect_ratio=inp.format)
    return str(out_path)


def _build_prompt(
    inp: BuildInput,
    ref: ReferenceLayout | None,
    variation_hint: str = "",
    force_human: bool | None = None,
) -> str:
    copy = inp.copy_deck
    # Reference is active if we have a parsed layout OR if a reference image path exists
    has_reference = (ref is not None) or bool(
        inp.reference_static_path and Path(inp.reference_static_path).exists()
    )

    # Copy block
    copy_lines = [f'- Headline: "{copy.headline}" — upper area, very bold, 2 lines, large']
    if copy.subhead:
        copy_lines.append(f'- Subhead: "{copy.subhead}" — below headline, regular weight, smaller')
    if copy.bottom_strip:
        strip_text = "  |  ".join(copy.bottom_strip[:3])
        copy_lines.append(f'- Bottom strip: "{strip_text}" — centered at very bottom, small, semi-bold')
    if copy.cta:
        copy_lines.append(f'- CTA: "{copy.cta}" — small black pill button below subhead')
    copy_lines.append('- Logo: "man matters®" — top-left, small, lowercase bold sans-serif')
    copy_lines.append('- Thin horizontal rule line above the bottom strip')
    copy_block = "\n".join(copy_lines)

    # Reference-informed composition
    if has_reference:
        ref_detail = ""
        if ref:
            ref_detail = f"\n- Reference mood: {ref.mood}\n- Reference notes: {ref.notes}"
        comp_block = f"""COMPOSITION (you MUST follow the reference image's layout structure):
- One of the attached images is a REFERENCE STATIC. Study it carefully.
- Replicate its EXACT compositional structure: where the product is positioned (left/right/center, size relative to canvas), where the headline sits, where the subhead sits, the visual hierarchy, the whitespace balance, the overall arrangement of elements.
- The reference's STRUCTURE is your layout blueprint. Copy the positions, proportions, and spatial relationships — NOT the reference's text, branding, colors, or product.
- If the reference shows the product on the left with text on the right, do that. If it shows the product centered with text above, do that. If it shows ingredients arranged around the product, do that.
- This is the most important instruction: the output's layout must be recognizably the same structure as the reference.{ref_detail}"""
    else:
        comp_block = """COMPOSITION:
- Jar: center-right, upright, hero, facing camera. Takes up ~40-50% of canvas height.
- Headline: upper-left third, bold, 2 lines
- Subhead: directly below headline, ~55% of headline size
- Clear breathing room between text and product
- No text overlapping the jar"""

    # Ingredient block
    ingredient_block = ""
    if inp.ingredients:
        ing_lines = []
        for kw in inp.ingredients:
            prop = get_prop(kw)
            if prop:
                ing_lines.append(f"- {prop.display_name}: {prop.description}")
        if ing_lines:
            ingredient_block = (
                "\nFEATURED INGREDIENTS (arrange these as real, physical elements near the jar):\n"
                + "\n".join(ing_lines)
                + "\nUse the attached ingredient reference photos for accurate rendering. "
                "Present them in small glass or ceramic dishes, or scattered directly on the surface.\n"
            )

    # Human figure
    include_human = force_human if force_human is not None else (inp.template_hint in ("D", "J", "F"))
    human_block = ""
    if include_human:
        human_block = """
HUMAN FIGURE:
- Include an Indian man, age 25-35, in the composition
- Natural, authentic look — not stock-photo or AI-plastic
- Natural skin texture with pores, realistic hair, slight asymmetry
- Expression and pose should match the emotional tone of the headline
- The human should feel integrated into the scene, not pasted
- Crop strategy: upper body or half body; avoid showing hands holding the product to prevent finger artifacts
- AVOID: plastic/waxy skin, extra fingers, perfect symmetry, uncanny expressions"""
    elif not include_human:
        human_block = "\nHUMAN FIGURE: none. Do NOT include any human, hand, or figure."

    # Background mood
    if inp.template_hint in ("C", "D"):
        bg = "dark charcoal/moody (#2D2825), dramatic lighting"
    elif inp.template_hint in ("E",):
        bg = "mountain/sky outdoor photography, aspirational"
    else:
        bg = "warm beige/cream (#F5F0E8 to #EDE8DC), soft studio lighting from upper-right"

    return f"""You are creating a premium advertising static for Man Matters Shilajit Gummies.

PRODUCT: Image 1 is the main product jar. The next images are close-up photos of the SAME jar from different angles showing label details. Study ALL of these carefully — every word, icon, and detail on the label must be reproduced accurately in your output. The jar has a matte black body and white cap. Render EXACTLY ONE jar — never duplicate it.

EXACT TEXT ON THE JAR LABEL (reproduce these words precisely on the jar):
Front panel (top to bottom):
- [Gluten Free icon] top-left
- "man matters®" — brand logo, large, lowercase, bold, white on black
- "active nutrition" — sub-brand, small, white, centered
- "SHILAJIT GUMMIES" — product name, large bold white text, centered
- "— ShilAbsorb™ Shilajit" — ingredient line with em-dash
- "— KSM-66® Ashwagandha" — ingredient line with em-dash
- [NO ADDED SUGAR badge] — small green/white badge, right side
- Three icons in a row: "Potent Fulvic Acid" | "100% Natural" | "Superior Absorption"
- "NUTRACEUTICAL" — small caps
- "Tamarind Flavour | ADULT" — small text
- "60 N Gummies | 1 month supply" — small text
- "MADE IN INDIA" — very small, bottom-right

{"CRITICAL — REFERENCE STATIC: One of the images after the label close-ups is a REFERENCE STATIC. This is your LAYOUT BLUEPRINT. You MUST replicate its compositional structure — product position, headline position, text hierarchy, element arrangement. Do NOT copy its text, branding, or product — only its spatial layout. Remaining images are Man Matters brand exemplars for visual tone." if has_reference else "STYLE REFERENCES: Remaining images are Man Matters brand exemplars — match their visual tone, palette, and editorial aesthetic."}

COPY TO RENDER (render every word exactly as written — no paraphrasing, no omitting, no extra words):
{copy_block}

BRAND GUIDELINES:
- Background: {bg}
- Text: near-black (#1C1C1C) for headlines, medium grey (#5A5A5A) for subhead
- Typography: clean geometric sans-serif like Inter or GT America. NO serif fonts ever.
- Aesthetic: premium, minimal, editorial product photography. Indian D2C wellness brand. Clean, confident, modern-masculine.

{comp_block}
{ingredient_block}
{human_block}
{variation_hint}

HARD RULES — violation is disqualifying:
- Exactly ONE jar. Not two. Not a pair.
- Every word of copy rendered exactly as written above — no synonyms, no missing words
- Sans-serif only throughout
- No extra text, claims, taglines, icons, or decorative elements beyond what is listed
- All text must be crisp, readable, correctly formed
- Product label on the jar must be as close to image 1 as possible

FORMAT: {inp.format} aspect ratio. High resolution, sharp, no grain.
OUTPUT: a single complete advertising static ready to ship."""
