"""Product image preparation.

The cardinal rule: the product is NEVER regenerated by the image model. We prepare
a clean alpha cutout here and composite it downstream. This guarantees zero label
distortion and zero silhouette hallucination.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

from PIL import Image

CACHE_DIR = Path(__file__).resolve().parents[2] / "outputs" / ".cutout_cache"


def _cache_path(src: Path) -> Path:
    h = hashlib.md5(src.read_bytes()).hexdigest()[:16]
    return CACHE_DIR / f"{src.stem}_{h}.png"


def prepare_cutout(src: Path, force: bool = False) -> Path:
    """Return a PNG path with the product isolated on transparent background.

    If the source is already transparent (e.g., supplied packshots), we pass through.
    Otherwise we run rembg.
    """
    src = Path(src)
    if not src.exists():
        raise FileNotFoundError(src)

    cached = _cache_path(src)
    if cached.exists() and not force:
        return cached

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    img = Image.open(src).convert("RGBA")

    if _has_meaningful_alpha(img):
        # Already cut out — just trim to content bbox and cache.
        img = _trim_to_content(img)
        img.save(cached, "PNG")
        return cached

    # Run rembg (lazy import — heavy)
    from rembg import remove  # type: ignore

    out_bytes = remove(src.read_bytes())
    cached.write_bytes(out_bytes)
    trimmed = _trim_to_content(Image.open(cached).convert("RGBA"))
    trimmed.save(cached, "PNG")
    return cached


def _has_meaningful_alpha(img: Image.Image) -> bool:
    """Heuristic: source already has transparency if >5% of pixels are transparent."""
    if img.mode != "RGBA":
        return False
    alpha = img.split()[-1]
    hist = alpha.histogram()
    transparent = sum(hist[:20])  # near-zero alpha
    total = sum(hist)
    return total > 0 and transparent / total > 0.05


def _trim_to_content(img: Image.Image) -> Image.Image:
    bbox = img.getbbox()
    return img.crop(bbox) if bbox else img
